import { defineMigration, patch, at, set } from "sanity/migrate";

// Maps exact Sanity project title → trilingual description.
// If a title doesn't match, the project is skipped (safe to re-run).
const DESCRIPTIONS: Record<string, { en: string; fr: string; nl: string }> = {
  "Glassware in the Wild": {
    en: "Studio Franche is the Antwerp-based glass blowing studio of designer Jeffe Van Holle, whose custom-blown pieces — glasses, vases, ashtrays — carry the particular warmth of objects made entirely by hand. For this project, I took his work out of the studio and into the wild, travelling through France and Spain with the pieces in tow. The result is a series of product photographs made at the coast and on the beach, between rocks, sand and water, in conditions as far from a controlled studio as possible. The contrast between the fragility of the glass and the rawness of the landscape is where these images live.",
    fr: "Studio Franche est l'atelier de soufflage de verre anversois du designer Jeffe Van Holle, dont les pièces soufflées sur mesure — verres, vases, cendriers — portent la chaleur particulière des objets entièrement façonnés à la main. Pour ce projet, j'ai emmené son travail hors de l'atelier et dans la nature, voyageant à travers la France et l'Espagne avec les pièces. Le résultat est une série de photographies de produits réalisées sur la côte et sur la plage, entre rochers, sable et eau, dans des conditions aussi éloignées que possible d'un studio contrôlé. C'est dans le contraste entre la fragilité du verre et la rudesse du paysage que ces images trouvent leur sens.",
    nl: "Studio Franche is het Antwerpse glasblazersatelier van designer Jeffe Van Holle, wiens op maat geblazen stukken — glazen, vazen, asbakken — de bijzondere warmte dragen van objecten die volledig met de hand zijn gemaakt. Voor dit project nam ik zijn werk mee buiten het atelier, op reis door Frankrijk en Spanje. Het resultaat is een reeks productfoto's gemaakt aan de kust en op het strand, tussen rotsen, zand en water, onder omstandigheden die zo ver mogelijk verwijderd zijn van een gecontroleerde studio. In het contrast tussen de breekbaarheid van het glas en de ruwheid van het landschap bevinden zich deze beelden.",
  },

  "Sunflower": {
    en: "Tamino and Angèle's \"Sunflower\" was one of the most visually ambitious music videos I've worked on as a still photographer. The production, directed with a painterly attention to light and landscape, brought both artists together in a setting that felt equal parts earthly and dreamlike. \"Sunflower\" went on to win the 2024 MIA Award for Best Music Video, a recognition that felt entirely deserved given the care that went into every frame of the production. These set photographs are a record of what it looked like from behind the lens.",
    fr: "\"Sunflower\" de Tamino et Angèle est l'un des clips les plus ambitieux visuellement sur lesquels j'ai travaillé en tant que photographe de plateau. La production, dirigée avec une attention picturale portée à la lumière et au paysage, a réuni les deux artistes dans un décor à la fois ancré et onirique. \"Sunflower\" a remporté le MIA Award 2024 du meilleur clip vidéo, une reconnaissance qui semblait tout à fait méritée compte tenu du soin apporté à chaque plan de la production. Ces photographies de plateau témoignent de ce que cela donnait depuis derrière l'objectif.",
    nl: "\"Sunflower\" van Tamino en Angèle is een van de visueel meest ambitieuze muziekvideo's waaraan ik als still photographer heb gewerkt. De productie, geregisseerd met een schilderachtige aandacht voor licht en landschap, bracht beide artiesten samen in een setting die zowel aards als dromerig aanvoelde. \"Sunflower\" won in 2024 de MIA Award voor beste muziekvideo, een erkenning die volledig verdiend leek gezien de zorg die in elk beeld van de productie werd gestoken. Deze setfoto's zijn een verslag van hoe het eruitzag van achter de lens.",
  },

  "The First Disciple": {
    en: "Tamino's \"The First Disciple\" called for something hauntingly intimate. Working as still photographer on this production, I was drawn into a visual world built on shadow, silence and restraint, qualities that run through Tamino's music as much as his imagery. The set photographs here reflect that atmosphere: close, quiet, and deliberately unhurried. An image from this production was selected for the cover of Tamino's album Sahar, released in 2023.",
    fr: "\"The First Disciple\" de Tamino appelait quelque chose d'une intimité envoûtante. Travaillant comme photographe de plateau sur cette production, j'ai été plongé dans un univers visuel construit sur l'ombre, le silence et la retenue, des qualités qui traversent autant la musique de Tamino que ses images. Les photographies de plateau présentées ici reflètent cette atmosphère : proches, silencieuses et délibérément sans précipitation. Une image de cette production a été sélectionnée pour la pochette de l'album Sahar de Tamino, sorti en 2023.",
    nl: "Tamino's \"The First Disciple\" vroeg om iets indrukwekkend intimiefs. Als still photographer op deze productie werd ik meegenomen in een visuele wereld opgebouwd uit schaduw, stilte en terughoudendheid, kwaliteiten die Tamino's muziek net zo goed kenmerken als zijn beeldtaal. De setfoto's hier weerspiegelen die sfeer: dichtbij, stil en bewust zonder haast. Een beeld van deze productie werd geselecteerd voor de albumhoes van Tamino's Sahar, uitgebracht in 2023.",
  },

  "You Don't Own Me": {
    en: "\"You Don't Own Me\" brought together two artists whose work shares a rare intensity: Tamino, whose music carries a raw, introspective weight, and Sidi Larbi Cherkaoui, the Belgian-Moroccan choreographer whose movement language is among the most powerful in contemporary dance. Working as still photographer on this production, I followed the tension between body, music and space that defined every moment on set. The result is a series of images that sit somewhere between music video photography and dance documentation.",
    fr: "\"You Don't Own Me\" a réuni deux artistes dont le travail partage une intensité rare : Tamino, dont la musique porte un poids brut et introspectif, et Sidi Larbi Cherkaoui, le chorégraphe belgo-marocain dont le langage du mouvement compte parmi les plus puissants de la danse contemporaine. Travaillant comme photographe de plateau sur cette production, j'ai suivi la tension entre le corps, la musique et l'espace qui a défini chaque moment sur le plateau. Le résultat est une série d'images qui se situent quelque part entre la photographie de clip et la documentation de danse.",
    nl: "\"You Don't Own Me\" bracht twee artiesten samen wiens werk een zeldzame intensiteit deelt: Tamino, wiens muziek een rauwe, introspectieve zwaarte draagt, en Sidi Larbi Cherkaoui, de Belgisch-Marokkaanse choreograaf wiens bewegingstaal tot de krachtigste in de hedendaagse dans behoort. Als still photographer op deze productie volgde ik de spanning tussen lichaam, muziek en ruimte die elk moment op de set bepaalde. Het resultaat is een reeks beelden die zich ergens bevinden tussen muziekvideofotografie en dansdocumentatie.",
  },

  "The Longing": {
    en: "\"The Longing\" is perhaps the most emotionally layered of the Tamino music videos I worked on as a still photographer. The production wove warmth and melancholy into the same frame, a quality that demanded patience and attentiveness from everyone on set. These photographs attempt to hold that same duality: the quiet ache of something beautiful that is already passing.",
    fr: "\"The Longing\" est peut-être le clip de Tamino sur lequel j'ai travaillé comme photographe de plateau le plus riche émotionnellement. La production tissait chaleur et mélancolie dans le même cadre, une qualité qui demandait patience et attention de la part de toute l'équipe sur le plateau. Ces photographies tentent de conserver cette même dualité : la douleur silencieuse de quelque chose de beau qui est déjà en train de passer.",
    nl: "\"The Longing\" is misschien wel de emotioneel meest gelaagde Tamino-muziekvideo waaraan ik als still photographer heb gewerkt. De productie weefde warmte en melancholie in hetzelfde beeld, een kwaliteit die geduld en aandacht vroeg van iedereen op de set. Deze foto's proberen diezelfde dualiteit vast te houden: de stille pijn van iets moois dat al aan het voorbijgaan is.",
  },

  "Custom Jewelry by Ayotito": {
    en: "Ayotito's jewelry begins long before the finished piece. Each creation moves through an intricate and deeply personal process, shaped by the designer's own hand from start to finish. This studio shoot presents a curated selection of his most celebrated work, photographed to let the craft speak for itself: the weight of the materials, the precision of the details, the quiet confidence of objects made with genuine intention.",
    fr: "Les bijoux d'Ayotito commencent bien avant la pièce finale. Chaque création traverse un processus complexe et profondément personnel, façonné de la main du designer du début à la fin. Cette série en studio présente une sélection de ses œuvres les plus remarquées, photographiée pour laisser le savoir-faire parler de lui-même : le poids des matériaux, la précision des détails, la confiance tranquille d'objets fabriqués avec une véritable intention.",
    nl: "Ayotito's sieraden beginnen lang voor het afgewerkte stuk. Elke creatie doorloopt een ingewikkeld en diepst persoonlijk proces, van begin tot eind gevormd door de hand van de designer zelf. Deze studioshoot presenteert een zorgvuldige selectie van zijn meest geprezen werk, gefotografeerd om het vakmanschap voor zichzelf te laten spreken: het gewicht van de materialen, de precisie van de details, het stille zelfvertrouwen van objecten gemaakt met oprechte intentie.",
  },

  "Nazook, a Stranger": {
    en: "Nazook was a stranger. I found him on the cliffs above the sea during a stormy evening, fishing alone in the fading light. We talked for an hour or two, and somewhere in that conversation I asked if I could take his portrait. He said yes. These photographs were made in that brief window of trust between two people who had just met and would never meet again.",
    fr: "Nazook était un inconnu. Je l'ai trouvé sur les falaises au-dessus de la mer lors d'une soirée orageuse, pêchant seul dans la lumière déclinante. Nous avons parlé pendant une heure ou deux, et quelque part dans cette conversation je lui ai demandé si je pouvais faire son portrait. Il a dit oui. Ces photographies ont été réalisées dans cette brève fenêtre de confiance entre deux personnes qui venaient de se rencontrer et ne se reverraient plus jamais.",
    nl: "Nazook was een vreemde. Ik vond hem op de kliffen boven de zee tijdens een stormachtige avond, alleen vissend in het wegstervende licht. We praatten een uur of twee, en ergens in dat gesprek vroeg ik of ik zijn portret mocht maken. Hij zei ja. Deze foto's werden gemaakt in dat korte venster van vertrouwen tussen twee mensen die elkaar net hadden ontmoet en elkaar nooit meer zouden zien.",
  },

  "Jules the Artist": {
    en: "Jules is a friend and a multidisciplinary artist, photographed here in the middle of making something. There is a particular kind of presence that artists have when they are working, an unselfconsciousness that is almost impossible to ask for and very easy to miss. Shot across both digital and analogue mediums, these portraits try to hold that quality: Jules as he actually is, goofy and focused and entirely himself.",
    fr: "Jules est un ami et un artiste pluridisciplinaire, photographié ici en plein travail de création. Il y a une présence particulière qu'ont les artistes lorsqu'ils travaillent, une absence de conscience de soi qu'il est presque impossible de demander et très facile de manquer. Réalisés sur des supports numériques et analogiques, ces portraits tentent de saisir cette qualité : Jules tel qu'il est vraiment, décontracté et concentré, entièrement lui-même.",
    nl: "Jules is een vriend en een multidisciplinair kunstenaar, hier gefotografeerd terwijl hij iets aan het maken was. Er is een bijzondere aanwezigheid die kunstenaars hebben wanneer ze aan het werk zijn, een onbewustheid die bijna onmogelijk te vragen is en heel gemakkelijk te missen. Gemaakt op zowel digitale als analoge media proberen deze portretten die kwaliteit vast te houden: Jules zoals hij werkelijk is, grappig en geconcentreerd en volledig zichzelf.",
  },

  "Alban, a Stranger": {
    en: "Alban and I spent two days together on the coast of Asturias in northern Spain, two strangers who crossed paths and then disappeared from each other's lives entirely. These portraits were made on a cold evening when he decided, without much warning, to go for a nude swim in the Atlantic. He was a unique character. As it happens, I was there to photograph the glassware for Studio Franche when Alban walked into the frame and made the day his own.",
    fr: "Alban et moi avons passé deux jours ensemble sur la côte des Asturies dans le nord de l'Espagne, deux inconnus dont les chemins se sont croisés avant de disparaître complètement de la vie l'un de l'autre. Ces portraits ont été réalisés un soir froid où il a décidé, sans beaucoup de prévenir, d'aller nager nu dans l'Atlantique. C'était un personnage unique. Il se trouve que j'étais là pour photographier les verreries pour Studio Franche quand Alban est entré dans le cadre et a fait de la journée la sienne.",
    nl: "Alban en ik brachten twee dagen samen door aan de kust van Asturië in het noorden van Spanje, twee vreemden wier paden kruisten en daarna volledig uit elkaars leven verdwenen. Deze portretten werden gemaakt op een koude avond toen hij besloot, zonder veel aankondiging, naakt te gaan zwemmen in de Atlantische Oceaan. Hij was een uniek personage. Toevallig was ik daar om het glaswerk voor Studio Franche te fotograferen toen Alban het kader binnenliep en de dag tot de zijne maakte.",
  },

  "La Familia": {
    en: "La Familia is an ongoing portrait project made across different analogue cameras and film stocks, tracing the faces of my own family. Grandparents from both sides, nephews, cousins, moments caught in kitchens and gardens and living rooms. Shot entirely on film, these portraits carry the particular tenderness of images made close to home, where the photographer is also a part of what is being documented.",
    fr: "La Familia est un projet de portrait en cours réalisé avec différents appareils analogiques et pellicules, retraçant les visages de ma propre famille. Grands-parents des deux côtés, neveux, cousins, moments saisis dans des cuisines, des jardins et des salons. Tournées entièrement sur pellicule, ces portraits portent la tendresse particulière des images faites près de chez soi, là où le photographe fait également partie de ce qui est documenté.",
    nl: "La Familia is een doorlopend portretproject gemaakt met verschillende analoge camera's en filmsoorten, dat de gezichten van mijn eigen familie in kaart brengt. Grootouders van beide kanten, neven, nichten, momenten gevangen in keukens en tuinen en woonkamers. Volledig op film geschoten dragen deze portretten de bijzondere tederheid van beelden gemaakt dicht bij huis, waar de fotograaf ook deel uitmaakt van wat gedocumenteerd wordt.",
  },

  "Sporza News Anchors": {
    en: "Sporza is the sports broadcasting platform of VRT, Belgium's public broadcaster, and one of the most recognised sports media brands in the country. This commissioned series of professional headshots covers both the newer faces joining the Sporza team and the anchors who have been part of the platform since the beginning. Shot to balance individual character with visual consistency across the full team, these portraits were made to work across broadcast, digital and editorial contexts.",
    fr: "Sporza est la plateforme de diffusion sportive de VRT, le radiodiffuseur public belge, et l'une des marques médiatiques sportives les plus reconnues du pays. Cette série de portraits professionnels commandée couvre à la fois les nouveaux visages rejoignant l'équipe Sporza et les présentateurs qui font partie de la plateforme depuis ses débuts. Réalisés pour équilibrer le caractère individuel et la cohérence visuelle de l'ensemble de l'équipe, ces portraits ont été conçus pour fonctionner dans des contextes de diffusion, numériques et éditoriaux.",
    nl: "Sporza is het sportuitzendplatform van VRT, de Belgische openbare omroep, en een van de meest herkende sportmediamerken in het land. Deze in opdracht gemaakte reeks professionele headshots omvat zowel de nieuwere gezichten die het Sporza-team komen versterken als de ankers die al vanaf het begin deel uitmaken van het platform. Gemaakt om individueel karakter en visuele consistentie over het volledige team in balans te brengen, werden deze portretten ontworpen om te werken in broadcast-, digitale en redactionele contexten.",
  },

  "Talvez": {
    en: "Talvez is a confrontation wrapped in a summer melody: the story of someone who has run from everything, and who runs into the past just when she believes she has finally escaped it. Working as a still photographer on this production, I followed that emotional undertow through every scene, looking for the images that held the tension between lightness and unresolved weight. \"Talvez você se lembra da minha escuridão.\" Maybe you only remember my darkness.",
    fr: "Talvez est une confrontation enveloppée dans une mélodie estivale : l'histoire de quelqu'un qui a fui tout, et qui tombe sur le passé au moment même où elle croit s'en être finalement échappée. Travaillant comme photographe de plateau sur cette production, j'ai suivi ce courant émotionnel à travers chaque scène, à la recherche des images qui retenaient la tension entre légèreté et poids non résolu. \"Talvez você se lembra da minha escuridão.\" Peut-être que tu ne te souviens que de mon obscurité.",
    nl: "Talvez is een confrontatie verpakt in een zomerse melodie: het verhaal van iemand die van alles is weggevlucht, en die het verleden tegenkomt net op het moment dat ze denkt er eindelijk aan ontsnapt te zijn. Als still photographer op deze productie volgde ik die emotionele onderstroom door elke scène, op zoek naar de beelden die de spanning vasthielden tussen lichtheid en onopgelost gewicht. \"Talvez você se lembra da minha escuridão.\" Misschien herinner je je alleen mijn duisternis.",
  },

  "Tom, a Friend": {
    en: "Tom is a friend. These are a few quiet portraits made in Brussels over a game of chess, shot on both analogue and digital. Nothing more than that, really. Sometimes a photograph doesn't need a brief.",
    fr: "Tom est un ami. Ce sont quelques portraits tranquilles réalisés à Bruxelles au cours d'une partie d'échecs, pris sur des supports analogiques et numériques. Rien de plus que ça, vraiment. Parfois une photographie n'a pas besoin d'un brief.",
    nl: "Tom is een vriend. Dit zijn een paar stille portretten gemaakt in Brussel tijdens een schaakspel, geschoten op zowel analoog als digitaal. Meer niet, eigenlijk. Soms heeft een foto geen briefing nodig.",
  },

  // "What Remains" exists as two separate projects in different categories.
  // Match by the full title including the em-dash suffix.
  "What Remains — Short Film": {
    en: "What Remains is a short film and dance piece by choreographer Zoë Demoustier, built around a simple and devastating premise: children who are beginning life sharing the stage with older dancers who are leaving it. Working as a still photographer on this production, I moved between the film set and the rehearsal space, documenting both the choreography and the quiet moments between. The result is a body of work that sits at the intersection of set photography and dance documentation, shaped by a piece that asks what the body holds and what it lets go.",
    fr: "What Remains est un court-métrage et une pièce de danse de la chorégraphe Zoë Demoustier, construit autour d'une prémisse simple et bouleversante : des enfants qui commencent la vie partageant la scène avec des danseurs plus âgés qui la quittent. Travaillant comme photographe de plateau sur cette production, je me suis déplacé entre le plateau de tournage et l'espace de répétition, documentant à la fois la chorégraphie et les moments silencieux entre les deux. Le résultat est un ensemble d'œuvres qui se situe à l'intersection de la photographie de plateau et de la documentation de danse, façonné par une pièce qui interroge ce que le corps retient et ce qu'il laisse partir.",
    nl: "What Remains is een kortfilm en dansstuk van choreografe Zoë Demoustier, gebouwd rond een eenvoudige en verwoestende premisse: kinderen die het leven beginnen en het podium delen met oudere dansers die het verlaten. Als still photographer op deze productie bewoog ik me tussen de filmset en de repetitieruimte, waarbij ik zowel de choreografie als de stille momenten daartussen documenteerde. Het resultaat is een reeks werken die zich bevindt op het snijvlak van setfotografie en dansdocumentatie, gevormd door een stuk dat vraagt wat het lichaam vasthoudt en wat het loslaat.",
  },

  "What Remains — The Dernière": {
    en: "This is the dernière, the final performance of Zoë Demoustier's dance piece What Remains. Commissioned to document the full story of the evening, I moved both in front of and behind the stage, following the group and its dynamics from the last rehearsal to the final bow. What you see here is not just a record of a performance but a portrait of a company at the end of something: the particular atmosphere of a last night that everyone in the room knows will not come again.",
    fr: "Voici la dernière, la représentation finale de la pièce de danse What Remains de Zoë Demoustier. Chargé de documenter l'histoire complète de la soirée, je me suis déplacé à la fois devant et derrière la scène, suivant le groupe et sa dynamique depuis la dernière répétition jusqu'à la révérence finale. Ce que vous voyez ici n'est pas seulement le témoignage d'une représentation, mais le portrait d'une compagnie à la fin de quelque chose : l'atmosphère particulière d'une dernière nuit que tous dans la salle savent ne plus jamais revenir.",
    nl: "Dit is de dernière, de laatste voorstelling van Zoë Demoustier's dansstuk What Remains. In opdracht om het volledige verhaal van de avond te documenteren, bewoog ik me zowel voor als achter het podium, waarbij ik de groep en zijn dynamiek volgde van de laatste repetitie tot de laatste buiging. Wat u hier ziet is niet alleen een verslag van een voorstelling, maar een portret van een gezelschap aan het einde van iets: de bijzondere sfeer van een laatste avond waarvan iedereen in de zaal weet dat die niet meer terugkomt.",
  },

  "20km Through Brussels": {
    en: "The 20km of Brussels is one of the largest running events in Belgium, drawing tens of thousands of participants through the streets of the capital each year. Commissioned by VRT, I documented both the VRT team members taking part and the wider atmosphere of the event: the crowd, the city, the energy of a day when Brussels belongs entirely to its runners. The approach was documentary throughout, finding the human moments inside a very large and very public occasion.",
    fr: "Le 20km de Bruxelles est l'un des plus grands événements de course à pied en Belgique, attirant chaque année des dizaines de milliers de participants dans les rues de la capitale. Commissionné par VRT, j'ai documenté à la fois les membres de l'équipe VRT qui y participaient et l'atmosphère générale de l'événement : la foule, la ville, l'énergie d'une journée où Bruxelles appartient entièrement à ses coureurs. L'approche était documentaire tout au long, à la recherche des moments humains au sein d'une occasion très grande et très publique.",
    nl: "De 20km door Brussel is een van de grootste loopevenementen van België, dat elk jaar tienduizenden deelnemers door de straten van de hoofdstad trekt. In opdracht van VRT documenteerde ik zowel de VRT-teamleden die deelnamen als de bredere sfeer van het evenement: de menigte, de stad, de energie van een dag waarop Brussel volledig toebehoort aan zijn lopers. De aanpak was doorlopend documentair, op zoek naar de menselijke momenten binnen een zeer groot en zeer publiek evenement.",
  },
};

export default defineMigration({
  title: "Seed project descriptions with EN/FR/NL text",
  documentTypes: ["project"],
  async *migrate(documents) {
    for await (const document of documents()) {
      const title = (document.title as string | undefined)?.trim();
      if (!title) continue;

      const desc = DESCRIPTIONS[title];
      if (!desc) {
        // No description defined for this project title — skip silently.
        continue;
      }

      yield patch(document._id, [
        at("description", set({ _type: "localeText", ...desc })),
      ]);
    }
  },
});
